### ISSUE TITLE
Add rubocop

### ISSUE THREAD

**Issue by MattIPv4** [MattIPv4/do_username#1]
We should add rubocop as a dev dependency so that we can test the code quality.

**Comment by kushagra-shukla** [comment]
As I understand, this requires adding some lines in gemfile right? I have never worked with ruby. I just searched a bit about adding dev dependencies. If it requires only adding some lines in gemfile then assign it to me. It shouldn't be too difficult. 😄

**Comment by brunoocasali** [comment]
@MattIPv4 I can work on it ;)

@kushagra-shukla one of the steps to add rubocop in a project is the addition of the gem but you must to refactor all the offenses that rubocop points out too.

**Comment by MattIPv4** [comment]
@brunoocasali go for it 👍
