### ISSUE TITLE
JavaScript: Add CI Workflow for JS Port

### ISSUE THREAD

**Issue by sudiptog81** [MattIPv4/do_username#18]
A workflow can be included to test the JavaScript version.

**Comment by MattIPv4** [comment]
Blocked by #16 (and/or #17)

**Comment by MattIPv4** [comment]
As part of this, we should add an `.nvmrc` file to the javascript directory, which can be used in the workflow to se the node version.

See https://github.com/MattIPv4/do_username/blob/master/.github/workflows/ruby-ci.yml (and https://github.com/do-community/bandwidth-tool/blob/master/.github/workflows/do-spaces-workflow.yml#L12-L19)
